################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/constellation

########################################################
#                    Constellation                     #
########################################################

### Select one Constellation By Id with all attributes (myths, stars, galaxies)
GET {{ endpoint }}/84

### Select all Constellations with all attributes (myths, stars, galaxies)
GET {{ endpoint }}/

### Select all Constellations names
GET {{ endpoint }}/names

### Insert favorite constellation
POST {{ endpoint }}/favorite
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NjIyNzg1MCwiZXhwIjoxNjU2MzE0MjUwfQ.QqXCqfJ9C29Hyj1f8ywqb4a9YQlIgBc689wBD489Il8

{
    "constellation_id": 1
}

### Select All favorites constellations
GET {{ endpoint }}/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NjI3NTYwMiwiZXhwIjoxNjU2MzYyMDAyfQ.5Ryf6U7BxaJA6SrGJwAuPfT8yW0MEv_WaZp_U2ZmjJI

### Delete favorite constellation
DELETE {{ endpoint }}/favorite/83
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA3Mzk3MzUsImV4cCI6MTY1MDgyNjEzNX0.tK4qgnJ3QwHStWZLLr4RnVM-SqW9YVorX_1GgS1UsW4