################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/place

########################################################
#                       Place                          #
########################################################

### Insert a place
POST {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NzIxNTM4NiwiZXhwIjoxNjU3MzAxNzg2fQ.LHa5KI-BCVRudHiEqdXFEhj_OOBlVx2IBSX_AE3fFTQ
content-type: application/json

{
    "name": "Chez julie",
    "address": "Bordeaux"
}

### Select all places
GET {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NzIxNTM4NiwiZXhwIjoxNjU3MzAxNzg2fQ.LHa5KI-BCVRudHiEqdXFEhj_OOBlVx2IBSX_AE3fFTQ

### Select a place
GET {{ endpoint }}/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NzIxNTM4NiwiZXhwIjoxNjU3MzAxNzg2fQ.LHa5KI-BCVRudHiEqdXFEhj_OOBlVx2IBSX_AE3fFTQ

### Update a place
PATCH {{ endpoint }}/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NzIxNTM4NiwiZXhwIjoxNjU3MzAxNzg2fQ.LHa5KI-BCVRudHiEqdXFEhj_OOBlVx2IBSX_AE3fFTQ
content-type: application/json

{
    "name": "A la maison",
    "address": "Nîmes"
}

### Delete a place
DELETE {{ endpoint }}/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA3Mzk3MzUsImV4cCI6MTY1MDgyNjEzNX0.tK4qgnJ3QwHStWZLLr4RnVM-SqW9YVorX_1GgS1UsW4
