################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/user

########################################################
#                         User                         #
########################################################

### Insert user
POST {{ endpoint }}/
content-type: application/json

{
    "firstname": "a",
    "lastname": "a",
    "email": "aa@gmail.com",
    "password": "xx",
    "role": "user",
    "notification": true
}

### Connect user
### If it's ok you he gets a token in the header => Authorization: Bearer [token]
POST {{ endpoint }}/login
content-type: application/json

{
    "email": "aa@gmail.com",
    "password": "xx"
}

### Disconnect user
GET {{ endpoint }}/logout
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3NiwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTE1Mjc2NzksImV4cCI6MTY1MTYxNDA3OX0.pveZfsyBNC0tTSq9_eMw4pfcbY-sOpgym_Lb0H9bgI0

### Select user
GET {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJhIiwibGFzdG5hbWUiOiJhIiwiZW1haWwiOiJhYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1NTM5OTE1MCwiZXhwIjoxNjU1NDg1NTUwfQ.ESsq-sWzABmweLQAAOK_fTNr26u85Is_ZiRYeWen6WU

### Update user
PATCH {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDM5NTM2NiwiZXhwIjoxNjUwNDgxNzY2fQ.dvUOtm1bA9VpJBjGv443LShCYIjnF0mAqSP8IuwdvkQ
content-type: application/json

{
    "firstname": "d",
    "lastname": "d",
    "email": "bb@gmail.com",
    "oldPassword": "yy",
    "newPassword": "xx"
}

### Delete user
DELETE {{ endpoint }}/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3NiwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTE1Mjc3MTUsImV4cCI6MTY1MTYxNDExNX0.OgYX6W8-zDogheT4XLN1S3BGBEYDyhq2Z9ZKes0JPBw
content-type: application/json

{
    "password": "xx"
}

###########################
#         ERROR           #
###########################

### Select user
GET {{ endpoint }}/

### Select user
GET {{ endpoint }}/
Authorization: Bearer qdfgsfds
